version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2
    

jobs:
  test-api:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run tests and collect coverage
          command: coverage run OnitamaSimulator/OnitamaSimulator/test/test.py
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t a0fb5f22-c434-45bc-aa82-2d5f2622a3d1





workflows:
  version: 2.
  build-test:
    jobs:
      - test-api
      
 
